{
  "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/37887",
  "repository_url": "https://api.github.com/repos/tensorflow/tensorflow",
  "labels_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/37887/labels{/name}",
  "comments_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/37887/comments",
  "events_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/37887/events",
  "html_url": "https://github.com/tensorflow/tensorflow/issues/37887",
  "id": 587427222,
  "node_id": "MDU6SXNzdWU1ODc0MjcyMjI=",
  "number": 37887,
  "title": "Wrong loss calculation with multi-output models when using model.fit.",
  "user": {
    "login": "Hongtao-Niro",
    "id": 50312913,
    "node_id": "MDQ6VXNlcjUwMzEyOTEz",
    "avatar_url": "https://avatars.githubusercontent.com/u/50312913?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Hongtao-Niro",
    "html_url": "https://github.com/Hongtao-Niro",
    "followers_url": "https://api.github.com/users/Hongtao-Niro/followers",
    "following_url": "https://api.github.com/users/Hongtao-Niro/following{/other_user}",
    "gists_url": "https://api.github.com/users/Hongtao-Niro/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Hongtao-Niro/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Hongtao-Niro/subscriptions",
    "organizations_url": "https://api.github.com/users/Hongtao-Niro/orgs",
    "repos_url": "https://api.github.com/users/Hongtao-Niro/repos",
    "events_url": "https://api.github.com/users/Hongtao-Niro/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Hongtao-Niro/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 473172988,
      "node_id": "MDU6TGFiZWw0NzMxNzI5ODg=",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/type:bug",
      "name": "type:bug",
      "color": "159b2e",
      "default": false,
      "description": "Bug"
    },
    {
      "id": 1097546578,
      "node_id": "MDU6TGFiZWwxMDk3NTQ2NTc4",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/comp:keras",
      "name": "comp:keras",
      "color": "0052cc",
      "default": false,
      "description": "Keras related issues"
    },
    {
      "id": 1605791310,
      "node_id": "MDU6TGFiZWwxNjA1NzkxMzEw",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/TF%202.1",
      "name": "TF 2.1",
      "color": "c2e0c6",
      "default": false,
      "description": "for tracking issues in 2.1 release"
    }
  ],
  "state": "closed",
  "locked": false,
  "assignee": {
    "login": "amahendrakar",
    "id": 57165142,
    "node_id": "MDQ6VXNlcjU3MTY1MTQy",
    "avatar_url": "https://avatars.githubusercontent.com/u/57165142?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/amahendrakar",
    "html_url": "https://github.com/amahendrakar",
    "followers_url": "https://api.github.com/users/amahendrakar/followers",
    "following_url": "https://api.github.com/users/amahendrakar/following{/other_user}",
    "gists_url": "https://api.github.com/users/amahendrakar/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/amahendrakar/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/amahendrakar/subscriptions",
    "organizations_url": "https://api.github.com/users/amahendrakar/orgs",
    "repos_url": "https://api.github.com/users/amahendrakar/repos",
    "events_url": "https://api.github.com/users/amahendrakar/events{/privacy}",
    "received_events_url": "https://api.github.com/users/amahendrakar/received_events",
    "type": "User",
    "site_admin": false
  },
  "assignees": [
    {
      "login": "amahendrakar",
      "id": 57165142,
      "node_id": "MDQ6VXNlcjU3MTY1MTQy",
      "avatar_url": "https://avatars.githubusercontent.com/u/57165142?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/amahendrakar",
      "html_url": "https://github.com/amahendrakar",
      "followers_url": "https://api.github.com/users/amahendrakar/followers",
      "following_url": "https://api.github.com/users/amahendrakar/following{/other_user}",
      "gists_url": "https://api.github.com/users/amahendrakar/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/amahendrakar/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/amahendrakar/subscriptions",
      "organizations_url": "https://api.github.com/users/amahendrakar/orgs",
      "repos_url": "https://api.github.com/users/amahendrakar/repos",
      "events_url": "https://api.github.com/users/amahendrakar/events{/privacy}",
      "received_events_url": "https://api.github.com/users/amahendrakar/received_events",
      "type": "User",
      "site_admin": false
    }
  ],
  "milestone": null,
  "comments": 4,
  "created_at": "2020-03-25T04:06:11Z",
  "updated_at": "2020-03-31T07:53:06Z",
  "closed_at": "2020-03-30T02:45:40Z",
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "**System information** \r\n- Have I written custom code: Yes, though the code sample below is adapted from an official tensorflow tutorial with minimal changes.\r\n- OS Platform and Distribution: Ubuntu 18.04 \r\n- TensorFlow installed from: official pip package, version 2.1.0\r\n- Python version: 3.6.9\r\n- CUDA/cuDNN version: CUDA 10.1, GTX 1070\r\n\r\n\r\n**Describe the current behavior**\r\nConsider the following mnist example\r\n```python\r\nimport numpy as np\r\nimport tensorflow as tf\r\n\r\ninputs = tf.keras.Input(shape=(784,), name='digits')\r\nx = tf.keras.layers.Dense(64, activation='relu', name='dense_1')(inputs)\r\nx = tf.keras.layers.Dense(64, activation='relu', name='dense_2')(x)\r\noutputs = tf.keras.layers.Dense(10, name='predictions', activation='softmax')(x)\r\nmodel = tf.keras.Model(inputs=inputs, outputs=outputs)\r\n\r\nmodel.compile(\r\n    optimizer=tf.keras.optimizers.SGD(),\r\n    loss={\"predictions\": tf.keras.losses.SparseCategoricalCrossentropy()},\r\n    metrics=[tf.keras.metrics.SparseCategoricalAccuracy(name=\"accuracy\")],\r\n)\r\n\r\n(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()\r\nx_train = x_train.reshape(60000, 784).astype('float32') / 255\r\nx_test = x_test.reshape(10000, 784).astype('float32') / 255\r\ny_train = y_train.astype('float32')\r\ny_test = y_test.astype('float32')\r\n\r\nx_val = x_train[-10000:]\r\ny_val = y_train[-10000:]\r\nx_train = x_train[:-10000]\r\ny_train = y_train[:-10000]\r\n\r\ntrain_dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train))\r\ntrain_dataset = train_dataset.shuffle(buffer_size=1024).repeat().batch(64)\r\n\r\nval_dataset = tf.data.Dataset.from_tensor_slices((x_val, y_val))\r\nval_dataset = val_dataset.batch(64, drop_remainder=True)\r\n\r\ntest_dataset = tf.data.Dataset.from_tensor_slices((x_test, y_test))\r\ntest_dataset = test_dataset.batch(64)\r\n\r\nmodel.fit(train_dataset, epochs=3, steps_per_epoch=1000, validation_data=val_dataset)\r\n```\r\nThe output is \r\n```bash\r\nEpoch 1/3\r\n1000/1000 [==============================] - 4s 4ms/step - loss: 0.9192 - accuracy: 0.7615 - val_loss: 0.4060 - val_accuracy: 0.8914\r\nEpoch 2/3\r\n1000/1000 [==============================] - 3s 3ms/step - loss: 0.3786 - accuracy: 0.8939 - val_loss: 0.3147 - val_accuracy: 0.9127\r\nEpoch 3/3\r\n1000/1000 [==============================] - 3s 3ms/step - loss: 0.3211 - accuracy: 0.9080 - val_loss: 0.2796 - val_accuracy: 0.9196\r\n```\r\nThis works just fine as the loss decreases and the accuracy increases.\r\n\r\nHowever, if I simply add another dummy output to the model, the training will become erroneous. Let's just change the model definition line to `model = tf.keras.Model(inputs=inputs, outputs=[x, outputs])`\r\n\r\nNow the output is:\r\n```bash\r\nWARNING:tensorflow:Output dense_2 missing from loss dictionary. We assume this was done on purpose. The fit and evaluate APIs will not be expecting any data to be passed to dense_2.\r\nEpoch 1/3\r\nWARNING:tensorflow:Gradients do not exist for variables ['predictions/kernel:0', 'predictions/bias:0'] when minimizing the loss.\r\nWARNING:tensorflow:Gradients do not exist for variables ['predictions/kernel:0', 'predictions/bias:0'] when minimizing the loss.\r\n1000/1000 [==============================] - 4s 4ms/step - loss: 5.7781 - predictions_loss: 5.7781 - predictions_accuracy: 0.1048 - val_loss: 5.5196 - val_predictions_loss: 5.5196 - val_predictions_accuracy: 0.1243\r\nEpoch 2/3\r\n1000/1000 [==============================] - 4s 4ms/step - loss: 5.3866 - predictions_loss: 5.3866 - predictions_accuracy: 0.1202 - val_loss: 5.2255 - val_predictions_loss: 5.2255 - val_predictions_accuracy: 0.0967\r\nEpoch 3/3\r\n1000/1000 [==============================] - 4s 4ms/step - loss: 5.1167 - predictions_loss: 5.1167 - predictions_accuracy: 0.0996 - val_loss: 5.1479 - val_predictions_loss: 5.1479 - val_predictions_accuracy: 0.0992\r\n```\r\nBasically the network is not trained at all because as the warning says: *Gradients do not exist for variables ['predictions/kernel:0', 'predictions/bias:0'] when minimizing the loss.*\r\n\r\n\r\n\r\n**Describe the expected behavior**\r\nThe expect behavior is that by adding additional outputs to the model should not affect the training process in anyway. Note that in `model.compile`, I specified the loss function using a dictionary, so I don't need to modify the rest of the code after adding a dummy output.\r\n\r\n\r\n",
  "closed_by": {
    "login": "Hongtao-Niro",
    "id": 50312913,
    "node_id": "MDQ6VXNlcjUwMzEyOTEz",
    "avatar_url": "https://avatars.githubusercontent.com/u/50312913?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Hongtao-Niro",
    "html_url": "https://github.com/Hongtao-Niro",
    "followers_url": "https://api.github.com/users/Hongtao-Niro/followers",
    "following_url": "https://api.github.com/users/Hongtao-Niro/following{/other_user}",
    "gists_url": "https://api.github.com/users/Hongtao-Niro/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Hongtao-Niro/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Hongtao-Niro/subscriptions",
    "organizations_url": "https://api.github.com/users/Hongtao-Niro/orgs",
    "repos_url": "https://api.github.com/users/Hongtao-Niro/repos",
    "events_url": "https://api.github.com/users/Hongtao-Niro/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Hongtao-Niro/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/37887/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/37887/timeline",
  "performed_via_github_app": null
}
