{
  "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/41958",
  "repository_url": "https://api.github.com/repos/tensorflow/tensorflow",
  "labels_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/41958/labels{/name}",
  "comments_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/41958/comments",
  "events_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/41958/events",
  "html_url": "https://github.com/tensorflow/tensorflow/issues/41958",
  "id": 670814901,
  "node_id": "MDU6SXNzdWU2NzA4MTQ5MDE=",
  "number": 41958,
  "title": "Keras evaluate method returns wrong value after loading a model",
  "user": {
    "login": "HKatoo",
    "id": 49549064,
    "node_id": "MDQ6VXNlcjQ5NTQ5MDY0",
    "avatar_url": "https://avatars.githubusercontent.com/u/49549064?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/HKatoo",
    "html_url": "https://github.com/HKatoo",
    "followers_url": "https://api.github.com/users/HKatoo/followers",
    "following_url": "https://api.github.com/users/HKatoo/following{/other_user}",
    "gists_url": "https://api.github.com/users/HKatoo/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/HKatoo/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/HKatoo/subscriptions",
    "organizations_url": "https://api.github.com/users/HKatoo/orgs",
    "repos_url": "https://api.github.com/users/HKatoo/repos",
    "events_url": "https://api.github.com/users/HKatoo/events{/privacy}",
    "received_events_url": "https://api.github.com/users/HKatoo/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 404586594,
      "node_id": "MDU6TGFiZWw0MDQ1ODY1OTQ=",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/stat:awaiting%20tensorflower",
      "name": "stat:awaiting tensorflower",
      "color": "f4b400",
      "default": false,
      "description": "Status  - Awaiting response from tensorflower"
    },
    {
      "id": 473172988,
      "node_id": "MDU6TGFiZWw0NzMxNzI5ODg=",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/type:bug",
      "name": "type:bug",
      "color": "159b2e",
      "default": false,
      "description": "Bug"
    },
    {
      "id": 1097546578,
      "node_id": "MDU6TGFiZWwxMDk3NTQ2NTc4",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/comp:keras",
      "name": "comp:keras",
      "color": "0052cc",
      "default": false,
      "description": "Keras related issues"
    },
    {
      "id": 1946362326,
      "node_id": "MDU6TGFiZWwxOTQ2MzYyMzI2",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/TF%202.3",
      "name": "TF 2.3",
      "color": "1d76db",
      "default": false,
      "description": "Issues related to TF 2.3"
    }
  ],
  "state": "closed",
  "locked": false,
  "assignee": {
    "login": "k-w-w",
    "id": 31663267,
    "node_id": "MDQ6VXNlcjMxNjYzMjY3",
    "avatar_url": "https://avatars.githubusercontent.com/u/31663267?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/k-w-w",
    "html_url": "https://github.com/k-w-w",
    "followers_url": "https://api.github.com/users/k-w-w/followers",
    "following_url": "https://api.github.com/users/k-w-w/following{/other_user}",
    "gists_url": "https://api.github.com/users/k-w-w/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/k-w-w/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/k-w-w/subscriptions",
    "organizations_url": "https://api.github.com/users/k-w-w/orgs",
    "repos_url": "https://api.github.com/users/k-w-w/repos",
    "events_url": "https://api.github.com/users/k-w-w/events{/privacy}",
    "received_events_url": "https://api.github.com/users/k-w-w/received_events",
    "type": "User",
    "site_admin": false
  },
  "assignees": [
    {
      "login": "k-w-w",
      "id": 31663267,
      "node_id": "MDQ6VXNlcjMxNjYzMjY3",
      "avatar_url": "https://avatars.githubusercontent.com/u/31663267?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/k-w-w",
      "html_url": "https://github.com/k-w-w",
      "followers_url": "https://api.github.com/users/k-w-w/followers",
      "following_url": "https://api.github.com/users/k-w-w/following{/other_user}",
      "gists_url": "https://api.github.com/users/k-w-w/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/k-w-w/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/k-w-w/subscriptions",
      "organizations_url": "https://api.github.com/users/k-w-w/orgs",
      "repos_url": "https://api.github.com/users/k-w-w/repos",
      "events_url": "https://api.github.com/users/k-w-w/events{/privacy}",
      "received_events_url": "https://api.github.com/users/k-w-w/received_events",
      "type": "User",
      "site_admin": false
    }
  ],
  "milestone": null,
  "comments": 5,
  "created_at": "2020-08-01T12:11:03Z",
  "updated_at": "2020-09-03T21:42:11Z",
  "closed_at": "2020-08-20T03:35:10Z",
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "**System information**\r\n- OS Platform : Windows10\r\n- TensorFlow installed from : source(pip in anaconda)\r\n- TensorFlow version : 2.3.0\r\n- Python version : 3.8.3\r\n\r\n**Describe the current behavior**\r\nKeras Sequential method:`evaluate()` returns wrong value after loading a model. value of loss is equal but metrics differs before and after the model is saved and loaded.\r\nI calculated the accuracy manually using sklearn.metrics and got the same value. Therefore, the problem seems to be in this method.\r\nIn the below code, the `acc1`, `acc2` are the same. However `acc1=0.863` and `acc2=0.086` in my environment.\r\n\r\n~~When I ran the code in colab, this issue was not occurred.~~\r\n\r\n**Describe the expected behavior**\r\nKeras Sequential method:`evaluate()` returns same value before and after the model is saved and loaded.\r\n\r\n**Standalone code to reproduce the issue**\r\nThis code is a modified version of this [tutorial](https://www.tensorflow.org/tutorials/keras/save_and_load) code to reproduce the issue.\r\nIf you run the code in the above tutorial on Windows10, I think you are able to reproduce the issue.\r\nFor your information, I comment on the results in my environment.\r\n\r\n```\r\nimport numpy as np\r\nimport tensorflow as tf\r\nfrom tensorflow import keras\r\nfrom sklearn.metrics import accuracy_score\r\n\r\n(train_images, train_labels),(test_images, test_labels) = tf.keras.datasets.mnist.load_data()\r\ntrain_labels = train_labels[:1000]\r\ntest_labels = test_labels[:1000]\r\ntrain_images = train_images[:1000].reshape(-1, 28 * 28) / 255.0\r\ntest_images = test_images[:1000].reshape(-1, 28 * 28) / 255.0\r\n\r\ndef create_model():\r\n    model = tf.keras.models.Sequential([\r\n        keras.layers.Dense(512, activation='relu', input_shape=(784,)),\r\n        keras.layers.Dropout(0.2),\r\n        keras.layers.Dense(10)\r\n    ])\r\n    model.compile(optimizer='adam',\r\n                  loss=tf.losses.SparseCategoricalCrossentropy(from_logits=True),\r\n                  metrics=['accuracy'])\r\n    return model\r\n\r\n# Create first model\r\nmodel = create_model()\r\nmodel.fit(train_images, train_labels, epochs=5)\r\n\r\nmodel.save('saved_model/my_model')\r\n\r\n# Create second model (load the saved model)\r\nnew_model = tf.keras.models.load_model('saved_model/my_model')\r\n\r\n# First model's results\r\nloss1, acc1 = model.evaluate(test_images, test_labels)\r\naccuracy_score1 = accuracy_score(test_labels, np.argmax(model.predict(test_images), axis=1))\r\n# loss1, acc1 = [0.4392167329788208, 0.8629999756813049]\r\n# accuracy_score1 = 0.863\r\n\r\n# Second model's results\r\nloss2, acc2 = new_model.evaluate(test_images, test_labels)                           \r\naccuracy_score2 = accuracy_score(test_labels, np.argmax(new_model.predict(test_images), axis=1))\r\n# loss2, acc2 = [0.4392167329788208, 0.0860000029206276] <- THIS!!!\r\n# accuracy_score2 = 0.863\r\n```\r\n\r\nWhy is this happening?\r\nCan you help me?\r\n",
  "closed_by": {
    "login": "HKatoo",
    "id": 49549064,
    "node_id": "MDQ6VXNlcjQ5NTQ5MDY0",
    "avatar_url": "https://avatars.githubusercontent.com/u/49549064?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/HKatoo",
    "html_url": "https://github.com/HKatoo",
    "followers_url": "https://api.github.com/users/HKatoo/followers",
    "following_url": "https://api.github.com/users/HKatoo/following{/other_user}",
    "gists_url": "https://api.github.com/users/HKatoo/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/HKatoo/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/HKatoo/subscriptions",
    "organizations_url": "https://api.github.com/users/HKatoo/orgs",
    "repos_url": "https://api.github.com/users/HKatoo/repos",
    "events_url": "https://api.github.com/users/HKatoo/events{/privacy}",
    "received_events_url": "https://api.github.com/users/HKatoo/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/41958/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/41958/timeline",
  "performed_via_github_app": null
}
