{
  "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/44501",
  "repository_url": "https://api.github.com/repos/tensorflow/tensorflow",
  "labels_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/44501/labels{/name}",
  "comments_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/44501/comments",
  "events_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/44501/events",
  "html_url": "https://github.com/tensorflow/tensorflow/issues/44501",
  "id": 733965897,
  "node_id": "MDU6SXNzdWU3MzM5NjU4OTc=",
  "number": 44501,
  "title": "Image artifact with tf.keras data augmentation",
  "user": {
    "login": "tjdurant",
    "id": 9451958,
    "node_id": "MDQ6VXNlcjk0NTE5NTg=",
    "avatar_url": "https://avatars.githubusercontent.com/u/9451958?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/tjdurant",
    "html_url": "https://github.com/tjdurant",
    "followers_url": "https://api.github.com/users/tjdurant/followers",
    "following_url": "https://api.github.com/users/tjdurant/following{/other_user}",
    "gists_url": "https://api.github.com/users/tjdurant/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/tjdurant/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/tjdurant/subscriptions",
    "organizations_url": "https://api.github.com/users/tjdurant/orgs",
    "repos_url": "https://api.github.com/users/tjdurant/repos",
    "events_url": "https://api.github.com/users/tjdurant/events{/privacy}",
    "received_events_url": "https://api.github.com/users/tjdurant/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 386191887,
      "node_id": "MDU6TGFiZWwzODYxOTE4ODc=",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/stat:awaiting%20response",
      "name": "stat:awaiting response",
      "color": "f4b400",
      "default": false,
      "description": "Status  - Awaiting response from author"
    },
    {
      "id": 473172988,
      "node_id": "MDU6TGFiZWw0NzMxNzI5ODg=",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/type:bug",
      "name": "type:bug",
      "color": "159b2e",
      "default": false,
      "description": "Bug"
    },
    {
      "id": 1097546578,
      "node_id": "MDU6TGFiZWwxMDk3NTQ2NTc4",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/comp:keras",
      "name": "comp:keras",
      "color": "0052cc",
      "default": false,
      "description": "Keras related issues"
    },
    {
      "id": 1946362326,
      "node_id": "MDU6TGFiZWwxOTQ2MzYyMzI2",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/TF%202.3",
      "name": "TF 2.3",
      "color": "1d76db",
      "default": false,
      "description": "Issues related to TF 2.3"
    },
    {
      "id": 2046763290,
      "node_id": "MDU6TGFiZWwyMDQ2NzYzMjkw",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/Fixed%20in%20Nightly",
      "name": "Fixed in Nightly",
      "color": "5ecc37",
      "default": false,
      "description": "Issues that are resolved in nightly version"
    }
  ],
  "state": "closed",
  "locked": false,
  "assignee": {
    "login": "ymodak",
    "id": 42785357,
    "node_id": "MDQ6VXNlcjQyNzg1MzU3",
    "avatar_url": "https://avatars.githubusercontent.com/u/42785357?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ymodak",
    "html_url": "https://github.com/ymodak",
    "followers_url": "https://api.github.com/users/ymodak/followers",
    "following_url": "https://api.github.com/users/ymodak/following{/other_user}",
    "gists_url": "https://api.github.com/users/ymodak/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ymodak/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ymodak/subscriptions",
    "organizations_url": "https://api.github.com/users/ymodak/orgs",
    "repos_url": "https://api.github.com/users/ymodak/repos",
    "events_url": "https://api.github.com/users/ymodak/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ymodak/received_events",
    "type": "User",
    "site_admin": false
  },
  "assignees": [
    {
      "login": "ymodak",
      "id": 42785357,
      "node_id": "MDQ6VXNlcjQyNzg1MzU3",
      "avatar_url": "https://avatars.githubusercontent.com/u/42785357?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ymodak",
      "html_url": "https://github.com/ymodak",
      "followers_url": "https://api.github.com/users/ymodak/followers",
      "following_url": "https://api.github.com/users/ymodak/following{/other_user}",
      "gists_url": "https://api.github.com/users/ymodak/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ymodak/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ymodak/subscriptions",
      "organizations_url": "https://api.github.com/users/ymodak/orgs",
      "repos_url": "https://api.github.com/users/ymodak/repos",
      "events_url": "https://api.github.com/users/ymodak/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ymodak/received_events",
      "type": "User",
      "site_admin": false
    }
  ],
  "milestone": null,
  "comments": 5,
  "created_at": "2020-11-01T13:26:29Z",
  "updated_at": "2020-11-03T19:27:29Z",
  "closed_at": "2020-11-03T19:27:28Z",
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "<em>Please make sure that this is a bug. As per our\r\n[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),\r\nwe only address code/doc bugs, performance issues, feature requests and\r\nbuild/installation issues on GitHub. tag:bug_template</em>\r\n\r\n**System information**\r\n- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes\r\n- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux\r\n- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A\r\n- TensorFlow installed from (source or binary): RUN pip install --upgrade tensorflow tensorflow-gpu\r\n- TensorFlow version (use command below): v2.3.0-54-gfcc4b966f1 2.3.1\r\n- Python version: Python 3.6\r\n- Bazel version (if compiling from source):\r\n- GCC/Compiler version (if compiling from source):\r\n- CUDA/cuDNN version: V10.1.243\r\n- GPU model and memory: GeForce GTX 108 / 261MiB / 11178MiB\r\n\r\nYou can collect some of this information using our environment capture\r\n[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)\r\nYou can also obtain the TensorFlow version with:\r\n1. TF 1.0: `python -c \"import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)\"`\r\n2. TF 2.0: `python -c \"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)\"`\r\n\r\n\r\n**Describe the current behavior**\r\n\r\nWhen using the following code: \r\n```\r\ndata_augmentation = tf.keras.Sequential([\r\n  tf.keras.layers.experimental.preprocessing.RandomFlip('horizontal'),\r\n  tf.keras.layers.experimental.preprocessing.RandomRotation(90),\r\n])\r\n```\r\nI see black lines around the edges of the augmented images. I do not see this when I use plain Keras:\r\n\r\n```\r\ndatagen = ImageDataGenerator(\r\n    rotation_range=model_params['rotation_range'],  # randomly rotate images in the range (degrees, 0 to 180)  \r\n    horizontal_flip=model_params['horizontal_flip'],  # randomly flip images\r\n    vertical_flip=model_params['vertical_flip'],\r\n\r\n)  \r\n```\r\n\r\nAlso, when I upgrade to tf-nightly it goes away. \r\n\r\n**Describe the expected behavior**\r\nI would expect the black lines to not be there. \r\n\r\n**Standalone code to reproduce the issue**\r\nProvide a reproducible test case that is the bare minimum necessary to generate\r\nthe problem. If possible, please share a link to Colab/Jupyter/any notebook.\r\n\r\nhttps://colab.research.google.com/drive/1nRpmyMrXkV43W82nI2fP2F05JndeGdg0?usp=sharing\r\n\r\n**Other info / logs** Include any logs or source code that would be helpful to\r\ndiagnose the problem. If including tracebacks, please include the full\r\ntraceback. Large logs and files should be attached.\r\n\r\nI guess my question is whether or not these black lines are truly being fed into the network when using data augmentation.",
  "closed_by": {
    "login": "tjdurant",
    "id": 9451958,
    "node_id": "MDQ6VXNlcjk0NTE5NTg=",
    "avatar_url": "https://avatars.githubusercontent.com/u/9451958?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/tjdurant",
    "html_url": "https://github.com/tjdurant",
    "followers_url": "https://api.github.com/users/tjdurant/followers",
    "following_url": "https://api.github.com/users/tjdurant/following{/other_user}",
    "gists_url": "https://api.github.com/users/tjdurant/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/tjdurant/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/tjdurant/subscriptions",
    "organizations_url": "https://api.github.com/users/tjdurant/orgs",
    "repos_url": "https://api.github.com/users/tjdurant/repos",
    "events_url": "https://api.github.com/users/tjdurant/events{/privacy}",
    "received_events_url": "https://api.github.com/users/tjdurant/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/44501/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/44501/timeline",
  "performed_via_github_app": null
}
