{
  "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/34619",
  "repository_url": "https://api.github.com/repos/tensorflow/tensorflow",
  "labels_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/34619/labels{/name}",
  "comments_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/34619/comments",
  "events_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/34619/events",
  "html_url": "https://github.com/tensorflow/tensorflow/issues/34619",
  "id": 528819969,
  "node_id": "MDU6SXNzdWU1Mjg4MTk5Njk=",
  "number": 34619,
  "title": "Wrong output printing when using fit_generator",
  "user": {
    "login": "andmax",
    "id": 1919506,
    "node_id": "MDQ6VXNlcjE5MTk1MDY=",
    "avatar_url": "https://avatars.githubusercontent.com/u/1919506?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/andmax",
    "html_url": "https://github.com/andmax",
    "followers_url": "https://api.github.com/users/andmax/followers",
    "following_url": "https://api.github.com/users/andmax/following{/other_user}",
    "gists_url": "https://api.github.com/users/andmax/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/andmax/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/andmax/subscriptions",
    "organizations_url": "https://api.github.com/users/andmax/orgs",
    "repos_url": "https://api.github.com/users/andmax/repos",
    "events_url": "https://api.github.com/users/andmax/events{/privacy}",
    "received_events_url": "https://api.github.com/users/andmax/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 404586594,
      "node_id": "MDU6TGFiZWw0MDQ1ODY1OTQ=",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/stat:awaiting%20tensorflower",
      "name": "stat:awaiting tensorflower",
      "color": "f4b400",
      "default": false,
      "description": "Status  - Awaiting response from tensorflower"
    },
    {
      "id": 473172988,
      "node_id": "MDU6TGFiZWw0NzMxNzI5ODg=",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/type:bug",
      "name": "type:bug",
      "color": "159b2e",
      "default": false,
      "description": "Bug"
    },
    {
      "id": 1097546578,
      "node_id": "MDU6TGFiZWwxMDk3NTQ2NTc4",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/comp:keras",
      "name": "comp:keras",
      "color": "0052cc",
      "default": false,
      "description": "Keras related issues"
    },
    {
      "id": 1548890241,
      "node_id": "MDU6TGFiZWwxNTQ4ODkwMjQx",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/TF%201.15",
      "name": "TF 1.15",
      "color": "e99695",
      "default": false,
      "description": "for issues seen on TF 1.15"
    }
  ],
  "state": "closed",
  "locked": false,
  "assignee": {
    "login": "omalleyt12",
    "id": 29100818,
    "node_id": "MDQ6VXNlcjI5MTAwODE4",
    "avatar_url": "https://avatars.githubusercontent.com/u/29100818?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/omalleyt12",
    "html_url": "https://github.com/omalleyt12",
    "followers_url": "https://api.github.com/users/omalleyt12/followers",
    "following_url": "https://api.github.com/users/omalleyt12/following{/other_user}",
    "gists_url": "https://api.github.com/users/omalleyt12/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/omalleyt12/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/omalleyt12/subscriptions",
    "organizations_url": "https://api.github.com/users/omalleyt12/orgs",
    "repos_url": "https://api.github.com/users/omalleyt12/repos",
    "events_url": "https://api.github.com/users/omalleyt12/events{/privacy}",
    "received_events_url": "https://api.github.com/users/omalleyt12/received_events",
    "type": "User",
    "site_admin": false
  },
  "assignees": [
    {
      "login": "omalleyt12",
      "id": 29100818,
      "node_id": "MDQ6VXNlcjI5MTAwODE4",
      "avatar_url": "https://avatars.githubusercontent.com/u/29100818?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/omalleyt12",
      "html_url": "https://github.com/omalleyt12",
      "followers_url": "https://api.github.com/users/omalleyt12/followers",
      "following_url": "https://api.github.com/users/omalleyt12/following{/other_user}",
      "gists_url": "https://api.github.com/users/omalleyt12/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/omalleyt12/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/omalleyt12/subscriptions",
      "organizations_url": "https://api.github.com/users/omalleyt12/orgs",
      "repos_url": "https://api.github.com/users/omalleyt12/repos",
      "events_url": "https://api.github.com/users/omalleyt12/events{/privacy}",
      "received_events_url": "https://api.github.com/users/omalleyt12/received_events",
      "type": "User",
      "site_admin": false
    }
  ],
  "milestone": null,
  "comments": 3,
  "created_at": "2019-11-26T16:01:20Z",
  "updated_at": "2020-02-28T19:38:24Z",
  "closed_at": "2020-02-28T19:38:22Z",
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "On TensorFlow 1.15 (OS Ubuntu 16.04), when I'm using generators to train a model via the tf.keras.model fit_generator() function call prints a wrong and duplicated output of \"Epoch 1\" when starting the validation steps on every epoch.  The function fit_generator() prints:\r\n\r\n```\r\nEpoch 1/2\r\nEpoch 1/2\r\n32/32 - 5s - loss: 2.3132 - val_loss: 2.3116\r\nEpoch 2/2\r\nEpoch 1/2\r\n32/32 - 1s - loss: 2.3070 - val_loss: 2.3075\r\n```\r\n\r\nThe minimal code to reproduce is:\r\n\r\n```\r\nimport math\r\nimport tensorflow as tf\r\nfrom tensorflow.keras.utils import to_categorical\r\n\r\n\r\ndef data_generator(X, Y, batch_size, start=0, end=None):\r\n    end = len(X) if end is None else end\r\n    num_batches = int(math.ceil((end-start)/batch_size))\r\n    while True:\r\n        lob = list(range(num_batches))\r\n        for bi in lob:\r\n            sb = start + bi*batch_size\r\n            eb = sb + batch_size\r\n            eb = end if eb > end else eb\r\n            Xb = X[sb:eb]\r\n            Yb = Y[sb:eb]\r\n            yield Xb, Yb\r\n\r\n\r\n(Xtr, Ytr), (Xva, Yva) = tf.keras.datasets.cifar10.load_data()\r\nXtr, Ytr, Xva, Yva, nc = Xtr[:1000], Ytr[:1000], Xva[:100], Yva[:100], 10\r\nXtr, Xva = Xtr.astype('float32') / 255, Xva.astype('float32') / 255\r\nYtr, Yva, ins = to_categorical(Ytr, nc), to_categorical(Yva, nc), Xtr.shape[1:]\r\n\r\nmodel = tf.keras.models.Sequential()\r\nmodel.add(tf.keras.layers.Input(ins))\r\nmodel.add(tf.keras.layers.Conv2D(8, (3, 3)))\r\nmodel.add(tf.keras.layers.Activation('relu'))\r\nmodel.add(tf.keras.layers.Conv2D(8, (3, 3), activation='relu'))\r\nmodel.add(tf.keras.layers.MaxPooling2D(pool_size=(2, 2)))\r\nmodel.add(tf.keras.layers.Dropout(0.25))\r\nmodel.add(tf.keras.layers.Conv2D(16, (3, 3), activation='relu'))\r\nmodel.add(tf.keras.layers.Conv2D(16, (3, 3), activation='relu'))\r\nmodel.add(tf.keras.layers.MaxPooling2D(pool_size=(2, 2)))\r\nmodel.add(tf.keras.layers.Dropout(0.25))\r\nmodel.add(tf.keras.layers.Flatten())\r\nmodel.add(tf.keras.layers.Dense(32, activation='relu'))\r\nmodel.add(tf.keras.layers.Dropout(0.5))\r\nmodel.add(tf.keras.layers.Dense(nc, activation='softmax'))\r\nopt = tf.keras.optimizers.RMSprop(lr=0.0001, decay=1e-6)\r\nmodel.compile(loss='categorical_crossentropy', optimizer=opt, metrics=[])\r\n\r\nbatch_size = 32\r\ntr_gen = data_generator(Xtr, Ytr, batch_size)\r\nva_gen = data_generator(Xva, Yva, batch_size)\r\ntr_steps = int(math.ceil(len(Xtr)/batch_size))\r\nva_steps = int(math.ceil(len(Xva)/batch_size))\r\n\r\nmodel.fit_generator(tr_gen, steps_per_epoch=tr_steps, epochs=2, verbose=2,\r\n                    validation_data=va_gen, validation_steps=va_steps)\r\n```\r\n\r\nIf I run it on TensorFlow 2.0, the duplicated and wrong prints disappear.",
  "closed_by": {
    "login": "omalleyt12",
    "id": 29100818,
    "node_id": "MDQ6VXNlcjI5MTAwODE4",
    "avatar_url": "https://avatars.githubusercontent.com/u/29100818?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/omalleyt12",
    "html_url": "https://github.com/omalleyt12",
    "followers_url": "https://api.github.com/users/omalleyt12/followers",
    "following_url": "https://api.github.com/users/omalleyt12/following{/other_user}",
    "gists_url": "https://api.github.com/users/omalleyt12/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/omalleyt12/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/omalleyt12/subscriptions",
    "organizations_url": "https://api.github.com/users/omalleyt12/orgs",
    "repos_url": "https://api.github.com/users/omalleyt12/repos",
    "events_url": "https://api.github.com/users/omalleyt12/events{/privacy}",
    "received_events_url": "https://api.github.com/users/omalleyt12/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/34619/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/34619/timeline",
  "performed_via_github_app": null
}
