{
  "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/33216",
  "repository_url": "https://api.github.com/repos/tensorflow/tensorflow",
  "labels_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/33216/labels{/name}",
  "comments_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/33216/comments",
  "events_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/33216/events",
  "html_url": "https://github.com/tensorflow/tensorflow/issues/33216",
  "id": 505393514,
  "node_id": "MDU6SXNzdWU1MDUzOTM1MTQ=",
  "number": 33216,
  "title": "[TF 2.0.0] Training keras Model on tf.data.Dataset causes small bug in logging",
  "user": {
    "login": "angeliand",
    "id": 17070767,
    "node_id": "MDQ6VXNlcjE3MDcwNzY3",
    "avatar_url": "https://avatars.githubusercontent.com/u/17070767?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/angeliand",
    "html_url": "https://github.com/angeliand",
    "followers_url": "https://api.github.com/users/angeliand/followers",
    "following_url": "https://api.github.com/users/angeliand/following{/other_user}",
    "gists_url": "https://api.github.com/users/angeliand/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/angeliand/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/angeliand/subscriptions",
    "organizations_url": "https://api.github.com/users/angeliand/orgs",
    "repos_url": "https://api.github.com/users/angeliand/repos",
    "events_url": "https://api.github.com/users/angeliand/events{/privacy}",
    "received_events_url": "https://api.github.com/users/angeliand/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 386191887,
      "node_id": "MDU6TGFiZWwzODYxOTE4ODc=",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/stat:awaiting%20response",
      "name": "stat:awaiting response",
      "color": "f4b400",
      "default": false,
      "description": "Status  - Awaiting response from author"
    },
    {
      "id": 473172988,
      "node_id": "MDU6TGFiZWw0NzMxNzI5ODg=",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/type:bug",
      "name": "type:bug",
      "color": "159b2e",
      "default": false,
      "description": "Bug"
    },
    {
      "id": 1097546578,
      "node_id": "MDU6TGFiZWwxMDk3NTQ2NTc4",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/comp:keras",
      "name": "comp:keras",
      "color": "0052cc",
      "default": false,
      "description": "Keras related issues"
    },
    {
      "id": 1114343535,
      "node_id": "MDU6TGFiZWwxMTE0MzQzNTM1",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/comp:data",
      "name": "comp:data",
      "color": "0052cc",
      "default": false,
      "description": "tf.data related issues"
    },
    {
      "id": 1160540362,
      "node_id": "MDU6TGFiZWwxMTYwNTQwMzYy",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/TF%202.0",
      "name": "TF 2.0",
      "color": "e79b38",
      "default": false,
      "description": "Issues relating to TensorFlow 2.0"
    }
  ],
  "state": "closed",
  "locked": false,
  "assignee": {
    "login": "jvishnuvardhan",
    "id": 46058173,
    "node_id": "MDQ6VXNlcjQ2MDU4MTcz",
    "avatar_url": "https://avatars.githubusercontent.com/u/46058173?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/jvishnuvardhan",
    "html_url": "https://github.com/jvishnuvardhan",
    "followers_url": "https://api.github.com/users/jvishnuvardhan/followers",
    "following_url": "https://api.github.com/users/jvishnuvardhan/following{/other_user}",
    "gists_url": "https://api.github.com/users/jvishnuvardhan/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/jvishnuvardhan/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/jvishnuvardhan/subscriptions",
    "organizations_url": "https://api.github.com/users/jvishnuvardhan/orgs",
    "repos_url": "https://api.github.com/users/jvishnuvardhan/repos",
    "events_url": "https://api.github.com/users/jvishnuvardhan/events{/privacy}",
    "received_events_url": "https://api.github.com/users/jvishnuvardhan/received_events",
    "type": "User",
    "site_admin": false
  },
  "assignees": [
    {
      "login": "jvishnuvardhan",
      "id": 46058173,
      "node_id": "MDQ6VXNlcjQ2MDU4MTcz",
      "avatar_url": "https://avatars.githubusercontent.com/u/46058173?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jvishnuvardhan",
      "html_url": "https://github.com/jvishnuvardhan",
      "followers_url": "https://api.github.com/users/jvishnuvardhan/followers",
      "following_url": "https://api.github.com/users/jvishnuvardhan/following{/other_user}",
      "gists_url": "https://api.github.com/users/jvishnuvardhan/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jvishnuvardhan/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jvishnuvardhan/subscriptions",
      "organizations_url": "https://api.github.com/users/jvishnuvardhan/orgs",
      "repos_url": "https://api.github.com/users/jvishnuvardhan/repos",
      "events_url": "https://api.github.com/users/jvishnuvardhan/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jvishnuvardhan/received_events",
      "type": "User",
      "site_admin": false
    }
  ],
  "milestone": null,
  "comments": 9,
  "created_at": "2019-10-10T16:55:09Z",
  "updated_at": "2019-11-01T19:07:39Z",
  "closed_at": "2019-11-01T19:07:37Z",
  "author_association": "CONTRIBUTOR",
  "active_lock_reason": null,
  "body": "<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>\r\n\r\n**System information**\r\n- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **No**\r\n- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Windows 10**\r\n- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **-**\r\n- TensorFlow installed from (source or binary): **binary**\r\n- TensorFlow version (use command below): **2.0.0**\r\n- Python version: **3.6.x**\r\n- CUDA/cuDNN version: **10.0/7.6.1**\r\n- GPU model and memory: \r\n\r\n\r\n---\r\n**Describe the current behavior**\r\n\r\nWhen fitting (.fit) a keras Model on a tf.data.Dataset, the dataset size is not inferred. Because of this, when setting `verbose=1`, during the first epoch the log becomes `current_step/Unknown`. Also the following is thrown (though it does not cause crashing):\r\n```\r\n[[{{node IteratorGetNext}}]]\r\n\t [[IteratorGetNext/_2]]\r\n2019-10-10 18:41:50.728985: W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Out of range: End of sequence\r\n\t [[{{node IteratorGetNext}}]]\r\n```\r\n**Describe the expected behavior**\r\n\r\nI would expect to see the number of samples/batches/etc.\r\n\r\n**Code to reproduce the issue**\r\n\r\nI created a small Colab notebook to demonstrate the issue: https://colab.research.google.com/drive/1-S787cE6BWhXJ_0BeAb6EGq4GaXAFwmu\r\nI recommend downloading the .py file and running it in command line (so colab logging doesn't interfere), because after the epoch is done, the correct batch number is found. The problem is during the epoch.\r\n \r\n**Other info / logs**\r\n\r\nI found that the dataset size inferring is actually run, but the returned value is not stored or used anywhere, it is only to throw a warning if the initialization made by the user is faulty in some way.\r\nI am referring to this line: [https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/python/keras/engine/training_v2.py#L247](https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/python/keras/engine/training_v2.py#L247)\r\nThe above problem would be eliminated with something like this (or the like):\r\n```\r\nsteps_per_epoch = training_utils.infer_steps_for_dataset(training_dataset, steps_per_epoch, \r\n                                                                                 steps_name='steps_per_epoch',epochs=0) \r\n                                                                            if steps_per_epoch is None else steps_per_epoch\r\n```\r\n",
  "closed_by": {
    "login": "tensorflow-copybara",
    "id": 33434372,
    "node_id": "MDQ6VXNlcjMzNDM0Mzcy",
    "avatar_url": "https://avatars.githubusercontent.com/u/33434372?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/tensorflow-copybara",
    "html_url": "https://github.com/tensorflow-copybara",
    "followers_url": "https://api.github.com/users/tensorflow-copybara/followers",
    "following_url": "https://api.github.com/users/tensorflow-copybara/following{/other_user}",
    "gists_url": "https://api.github.com/users/tensorflow-copybara/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/tensorflow-copybara/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/tensorflow-copybara/subscriptions",
    "organizations_url": "https://api.github.com/users/tensorflow-copybara/orgs",
    "repos_url": "https://api.github.com/users/tensorflow-copybara/repos",
    "events_url": "https://api.github.com/users/tensorflow-copybara/events{/privacy}",
    "received_events_url": "https://api.github.com/users/tensorflow-copybara/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/33216/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/33216/timeline",
  "performed_via_github_app": null
}
