{
  "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/35833",
  "repository_url": "https://api.github.com/repos/tensorflow/tensorflow",
  "labels_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/35833/labels{/name}",
  "comments_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/35833/comments",
  "events_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/35833/events",
  "html_url": "https://github.com/tensorflow/tensorflow/issues/35833",
  "id": 549185982,
  "node_id": "MDU6SXNzdWU1NDkxODU5ODI=",
  "number": 35833,
  "title": "Keras Estimator fails on regression task while underlying model works",
  "user": {
    "login": "adomasbaliuka",
    "id": 52975890,
    "node_id": "MDQ6VXNlcjUyOTc1ODkw",
    "avatar_url": "https://avatars.githubusercontent.com/u/52975890?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/adomasbaliuka",
    "html_url": "https://github.com/adomasbaliuka",
    "followers_url": "https://api.github.com/users/adomasbaliuka/followers",
    "following_url": "https://api.github.com/users/adomasbaliuka/following{/other_user}",
    "gists_url": "https://api.github.com/users/adomasbaliuka/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/adomasbaliuka/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/adomasbaliuka/subscriptions",
    "organizations_url": "https://api.github.com/users/adomasbaliuka/orgs",
    "repos_url": "https://api.github.com/users/adomasbaliuka/repos",
    "events_url": "https://api.github.com/users/adomasbaliuka/events{/privacy}",
    "received_events_url": "https://api.github.com/users/adomasbaliuka/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 473172988,
      "node_id": "MDU6TGFiZWw0NzMxNzI5ODg=",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/type:bug",
      "name": "type:bug",
      "color": "159b2e",
      "default": false,
      "description": "Bug"
    },
    {
      "id": 1097546578,
      "node_id": "MDU6TGFiZWwxMDk3NTQ2NTc4",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/comp:keras",
      "name": "comp:keras",
      "color": "0052cc",
      "default": false,
      "description": "Keras related issues"
    },
    {
      "id": 1548890241,
      "node_id": "MDU6TGFiZWwxNTQ4ODkwMjQx",
      "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/TF%201.15",
      "name": "TF 1.15",
      "color": "e99695",
      "default": false,
      "description": "for issues seen on TF 1.15"
    }
  ],
  "state": "closed",
  "locked": false,
  "assignee": {
    "login": "jvishnuvardhan",
    "id": 46058173,
    "node_id": "MDQ6VXNlcjQ2MDU4MTcz",
    "avatar_url": "https://avatars.githubusercontent.com/u/46058173?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/jvishnuvardhan",
    "html_url": "https://github.com/jvishnuvardhan",
    "followers_url": "https://api.github.com/users/jvishnuvardhan/followers",
    "following_url": "https://api.github.com/users/jvishnuvardhan/following{/other_user}",
    "gists_url": "https://api.github.com/users/jvishnuvardhan/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/jvishnuvardhan/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/jvishnuvardhan/subscriptions",
    "organizations_url": "https://api.github.com/users/jvishnuvardhan/orgs",
    "repos_url": "https://api.github.com/users/jvishnuvardhan/repos",
    "events_url": "https://api.github.com/users/jvishnuvardhan/events{/privacy}",
    "received_events_url": "https://api.github.com/users/jvishnuvardhan/received_events",
    "type": "User",
    "site_admin": false
  },
  "assignees": [
    {
      "login": "jvishnuvardhan",
      "id": 46058173,
      "node_id": "MDQ6VXNlcjQ2MDU4MTcz",
      "avatar_url": "https://avatars.githubusercontent.com/u/46058173?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jvishnuvardhan",
      "html_url": "https://github.com/jvishnuvardhan",
      "followers_url": "https://api.github.com/users/jvishnuvardhan/followers",
      "following_url": "https://api.github.com/users/jvishnuvardhan/following{/other_user}",
      "gists_url": "https://api.github.com/users/jvishnuvardhan/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jvishnuvardhan/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jvishnuvardhan/subscriptions",
      "organizations_url": "https://api.github.com/users/jvishnuvardhan/orgs",
      "repos_url": "https://api.github.com/users/jvishnuvardhan/repos",
      "events_url": "https://api.github.com/users/jvishnuvardhan/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jvishnuvardhan/received_events",
      "type": "User",
      "site_admin": false
    }
  ],
  "milestone": null,
  "comments": 5,
  "created_at": "2020-01-13T21:16:01Z",
  "updated_at": "2020-03-20T08:29:24Z",
  "closed_at": "2020-03-20T08:29:22Z",
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "**System information**\r\n- Have I written custom code: Yes\r\n- OS Platform and Distribution: Windows 10\r\n- TensorFlow installed from: binary\r\n- TensorFlow version: Same issue using tf2.0.0-beta1-cpu\r\n and tf1.14.0-gpu\r\n- Python version: 3.6.9\r\n- CUDA/cuDNN version: CUDA 10.1.168/cuDNN 7.6.2\r\n- GPU model and memory: NVIDIA GeForce RTX 2060, 6GB dedicated memory\r\n\r\n**Describe the current behavior**\r\nA convolutional reggression (last layer has linear activation and one neuron) network built with tf.keras is shown to fit the MNIST dataset (I know that MNIST is a classification task; this is an example) when converted to a dataset.\r\n\r\nWhen the same model is packaged into an estimator using  `tf.keras.estimator.model_to_estimator` no error messages occur, however the model no longer fits. The loss does not decrease.\r\n\r\nI had made a Stackoverflow question about this (https://stackoverflow.com/q/59631744/9988487) with no traction whatsoever. After some more trying to get it to work, I believe it is a bug.\r\n\r\n**Describe the expected behavior**\r\nThe keras estimator should have the same behaviour as the underlying model. Change the USE_ESTIMATOR variable to see that the underlying model works.\r\n**Code to reproduce the issue**\r\n```\r\n# python 3.6. Tested with tensorflow-gpu-1.14 and tensorflow-cpu-2.0\r\nimport tensorflow as tf\r\nimport numpy as np\r\n\r\n\r\ndef get_model(IM_WIDTH=28, num_color_channels=1):\r\n    \"\"\"Create a very simple convolutional neural network using a tf.keras Functional Model.\"\"\"\r\n    input = tf.keras.Input(shape=(IM_WIDTH, IM_WIDTH, num_color_channels))\r\n    x = tf.keras.layers.Conv2D(32, 3, activation='relu')(input)\r\n    x = tf.keras.layers.MaxPooling2D(3)(x)\r\n    x = tf.keras.layers.Conv2D(64, 3, activation='relu')(x)\r\n    x = tf.keras.layers.MaxPooling2D(3)(x)\r\n    x = tf.keras.layers.Flatten()(x)\r\n    x = tf.keras.layers.Dense(64, activation='relu')(x)\r\n    output = tf.keras.layers.Dense(1, activation='linear')(x)\r\n    model = tf.keras.Model(inputs=[input], outputs=[output])\r\n    model.compile(optimizer='adam', loss=\"mae\",\r\n                  metrics=['mae'])\r\n    model.summary()\r\n    return model\r\n\r\n\r\ndef input_fun(train=True):\r\n    \"\"\"Load MNIST and return the training or test set as a tf.data.Dataset; Valid input function for tf.estimator\"\"\"\r\n    (train_images, train_labels), (eval_images, eval_labels) = tf.keras.datasets.mnist.load_data()\r\n    train_images = train_images.reshape((60_000, 28, 28, 1)).astype(np.float32) / 255.\r\n    eval_images = eval_images.reshape((10_000, 28, 28, 1)).astype(np.float32) / 255.\r\n    # train_labels = train_labels.astype(np.float32)  # these two lines don't affect behaviour.\r\n    # eval_labels = eval_labels.astype(np.float32)\r\n    # For a neural network with one neuron in the final layer, it doesn't seem to matter if target data is float or int.\r\n\r\n    if train:\r\n        dataset = tf.data.Dataset.from_tensor_slices((train_images, train_labels))\r\n        dataset = dataset.shuffle(buffer_size=100).repeat(None).batch(32).prefetch(1)\r\n    else:\r\n        dataset = tf.data.Dataset.from_tensor_slices((eval_images, eval_labels))\r\n        dataset = dataset.batch(32).prefetch(1)  # note: prefetching does not affect behaviour\r\n\r\n    return dataset\r\n\r\n\r\nmodel = get_model()\r\ntrain_input_fn = lambda: input_fun(train=True)\r\neval_input_fn = lambda: input_fun(train=False)\r\n\r\nNUM_EPOCHS, STEPS_PER_EPOCH = 4, 1875  # 1875 = number_of_train_images(=60.000)  /  batch_size(=32)\r\nUSE_ESTIMATOR = False  # change this to compare model/estimator. Estimator performs much worse for no apparent reason\r\nif USE_ESTIMATOR:\r\n    estimator = tf.keras.estimator.model_to_estimator(\r\n        keras_model=model, model_dir=\"model_directory\",\r\n        config=tf.estimator.RunConfig(save_checkpoints_steps=200, save_summary_steps=200))\r\n\r\n    train_spec = tf.estimator.TrainSpec(input_fn=train_input_fn, max_steps=STEPS_PER_EPOCH * NUM_EPOCHS)\r\n    eval_spec = tf.estimator.EvalSpec(input_fn=eval_input_fn, throttle_secs=0)\r\n\r\n    tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)\r\n    print(\"Training complete. Evaluating Estimator:\")\r\n    print(estimator.evaluate(eval_input_fn))\r\n    # final train loss with estimator: ~2.5 (mean abs. error).\r\nelse:\r\n    dataset = train_input_fn()\r\n    model.fit(dataset, steps_per_epoch=STEPS_PER_EPOCH, epochs=NUM_EPOCHS)\r\n    print(\"Training complete. Evaluating Keras model:\")\r\n    print(model.evaluate(eval_input_fn()))\r\n    # final train loss with Keras model: ~0.4 (mean abs. error).\r\n```\r\n",
  "closed_by": {
    "login": "adomasbaliuka",
    "id": 52975890,
    "node_id": "MDQ6VXNlcjUyOTc1ODkw",
    "avatar_url": "https://avatars.githubusercontent.com/u/52975890?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/adomasbaliuka",
    "html_url": "https://github.com/adomasbaliuka",
    "followers_url": "https://api.github.com/users/adomasbaliuka/followers",
    "following_url": "https://api.github.com/users/adomasbaliuka/following{/other_user}",
    "gists_url": "https://api.github.com/users/adomasbaliuka/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/adomasbaliuka/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/adomasbaliuka/subscriptions",
    "organizations_url": "https://api.github.com/users/adomasbaliuka/orgs",
    "repos_url": "https://api.github.com/users/adomasbaliuka/repos",
    "events_url": "https://api.github.com/users/adomasbaliuka/events{/privacy}",
    "received_events_url": "https://api.github.com/users/adomasbaliuka/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/tensorflow/tensorflow/issues/35833/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/35833/timeline",
  "performed_via_github_app": null
}
